server:
  port: 5556

spring:
  application:
    name: zuul-services

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
zuul:
  host:
    socket-timeout-millis: 4000
    connect-timeout-millis: 6000
  routes:
#    cache-services:
#      path: /cache-services/**
#      serviceId: cache-services
    message-services:
      path: /message-services/**
      serviceId: message-services
#    user-services:
#      path: /user-services/**
#      serviceId: user-services
#    order-services:
#      path: /order-services/**
#      serviceId: order-services
#    crm-services:
#      path: /crm-services/**
#      serviceId: crm-services
  #需要忽略的头部信息，不在传播到其他服务
    sensitive-headers: Access-Control-Allow-Origin
    ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
